from .gastos import TOOLS_SCHEMA as _GASTOS_SCHEMA, HANDLERS as _GASTOS_HANDLERS
from .vencimientos import TOOLS_SCHEMA as _VENC_SCHEMA, HANDLERS as _VENC_HANDLERS
from .ingresos import TOOLS_SCHEMA as _ING_SCHEMA, HANDLERS as _ING_HANDLERS

TOOLS_SCHEMA = _GASTOS_SCHEMA + _VENC_SCHEMA + _ING_SCHEMA
HANDLERS = {**_GASTOS_HANDLERS, **_VENC_HANDLERS, **_ING_HANDLERS}

__all__ = ["TOOLS_SCHEMA", "HANDLERS"]
